name: Zip Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create archive of latest release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        path: './zenrush'
        filename: 'zenrush.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Create latest release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "zenrush.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
